# netlify.toml – Konfiguration für Netlify Build & Deploy

[build]
  publish = "."                      # Statischer Output liegt im Root (index.html)
  functions = "netlify/functions"    # Functions-Verzeichnis

# Stelle sicher, dass die JSON-Regeln mit ins Build gehen
[[functions]]
  included_files = ["netlify/functions/energiepilot_rules.json"]

# Optional: Security-Header (hatte ich vorher schon schlank ergänzt)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Optional: SPA-Redirect (nur nötig, falls du später Client-Routing nutzt)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
