# netlify.toml — minimal & stabil

[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  # falls du die JSON sicher mitnehmen willst (optional)
  included_files = ["netlify/functions/energiepilot_rules.json"]

# (optional) HTML nicht cachen, damit Änderungen sofort sichtbar sind
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"
