# netlify.toml — minimal & stabil

[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/energiepilot_rules.json"]

# HTML nicht cachen, damit Änderungen sofort sichtbar sind
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"
